if [ "$(tty)" = "/dev/tty1" ]; then
    exec uwsm start sway.desktop
fi

set -a
for conf in ~/.config/environment/common/*.conf; do
    [ -f "$conf" ] && source "$conf"
done

for conf in ~/.config/environment/shell/*.conf; do
    [ -f "$conf" ] && source "$conf"
done
set +a